import React, { useState, useRef, useEffect } from 'react';
import { HelpCircle } from 'lucide-react';

// ---------------------------------------------------------------------------
// Help text definitions for security terms used in the DSOP wizard
// ---------------------------------------------------------------------------

export const HELP_TEXT: Record<string, { title: string; body: string }> = {
  SAST: {
    title: 'SAST — Static Application Security Testing',
    body:
      'Scans your source code for security vulnerabilities without running it. Uses Semgrep to detect issues like SQL injection, hard-coded credentials, insecure crypto, and command injection. Runs on the raw code before a container is built.',
  },
  Secrets: {
    title: 'Secrets Scanning',
    body:
      'Uses Gitleaks to scan your repository history and working tree for accidentally committed credentials — API keys, passwords, tokens, private keys. Even deleted secrets remain in Git history and must be rotated.',
  },
  SBOM: {
    title: 'SBOM — Software Bill of Materials',
    body:
      'A machine-readable inventory of every library and dependency bundled inside your container image, generated by Syft in SPDX format. Required for ATO packages so auditors can check which software components are in use and respond quickly to new CVEs (e.g., Log4Shell).',
  },
  CVE: {
    title: 'CVE Scanning — Common Vulnerabilities and Exposures',
    body:
      'Trivy scans your container image layers for packages with known vulnerabilities published in the National Vulnerability Database. CRITICAL and HIGH findings block deployment. MEDIUM findings generate warnings. Upgrade the affected package or switch to a minimal base image (e.g., Chainguard, distroless) to reduce your attack surface.',
  },
  DAST: {
    title: 'DAST — Dynamic Application Security Testing',
    body:
      'Tests your running application by sending attack payloads to its HTTP endpoints. Uses OWASP ZAP to detect issues like XSS, SQL injection, open redirects, and missing security headers — issues that only appear at runtime. Requires the app to be accessible over HTTP.',
  },
  ISSM: {
    title: 'ISSM Review — Information System Security Manager',
    body:
      'A human review by the designated security officer (ISSM) before deployment to a classified or CUI environment. The ISSM verifies the scan results, reviews any accepted risks, and provides written authorization. This step is required by NIST 800-37 (RMF) for systems handling CUI or higher.',
  },
  ISSM_REVIEW: {
    title: 'ISSM Review — Information System Security Manager',
    body:
      'A human review by the designated security officer (ISSM) before deployment to a classified or CUI environment. The ISSM verifies the scan results, reviews any accepted risks, and provides written authorization. This step is required by NIST 800-37 (RMF) for systems handling CUI or higher.',
  },
  Cosign: {
    title: 'Cosign — Container Image Signing',
    body:
      'Signs your container image with a cryptographic key after it passes all scans. The signature is stored in the registry alongside the image. Kyverno enforces that every Pod must use a signed image — unsigned images are rejected at admission time. This ensures only pipeline-vetted images can run on the cluster.',
  },
  'FIPS 199': {
    title: 'FIPS 199 — Security Categorization',
    body:
      'A Federal standard that requires every system to be categorized by the potential impact (Low / Moderate / High) of a security breach on Confidentiality, Integrity, and Availability. This determines which NIST 800-53 controls apply and how rigorously they must be implemented. Required for all federal systems under FISMA.',
  },
  mTLS: {
    title: 'mTLS — Mutual TLS',
    body:
      'Unlike standard TLS where only the server proves its identity, mTLS requires both sides to present certificates. Istio enforces STRICT mTLS between every pod on this cluster — all in-cluster traffic is encrypted in transit and every workload has a cryptographic identity (SPIFFE SVID). This satisfies NIST SC-8 and SC-13.',
  },
  Kyverno: {
    title: 'Kyverno — Kubernetes Policy Engine',
    body:
      'A Kubernetes-native admission controller that validates, mutates, and generates resources using YAML policies. It enforces security rules like "no privileged containers," "images must be signed," and "all pods must have resource limits" at the time a resource is created. Policies are mapped to NIST 800-53 controls.',
  },
  PolicyException: {
    title: 'Kyverno PolicyException',
    body:
      'A signed, time-limited override that lets a specific workload bypass a Kyverno policy — for example, allowing a legacy tool to run as root. Exceptions must be submitted as a PR, reviewed by the ISSM, and include a justification and expiry date. They are audited and auto-expire after 90 days.',
  },
};

// ---------------------------------------------------------------------------
// HelpTooltip component
// ---------------------------------------------------------------------------

interface HelpTooltipProps {
  /** The key into HELP_TEXT, or pass title/body directly */
  term?: string;
  /** Override title (used when term is not in HELP_TEXT) */
  title?: string;
  /** Override body */
  body?: string;
  /** If true, renders children as the trigger instead of the HelpCircle icon */
  children?: React.ReactNode;
  /** Additional class applied to the trigger wrapper */
  className?: string;
}

export function HelpTooltip({ term, title, body, children, className = '' }: HelpTooltipProps) {
  const [visible, setVisible] = useState(false);
  const [position, setPosition] = useState<'top' | 'bottom'>('top');
  const triggerRef = useRef<HTMLSpanElement>(null);
  const tooltipRef = useRef<HTMLDivElement>(null);

  const info = term ? HELP_TEXT[term] : null;
  const resolvedTitle = title ?? info?.title ?? term ?? '';
  const resolvedBody = body ?? info?.body ?? '';

  // Decide whether to show above or below based on available space
  useEffect(() => {
    if (!visible || !triggerRef.current) return;
    const rect = triggerRef.current.getBoundingClientRect();
    setPosition(rect.top < 160 ? 'bottom' : 'top');
  }, [visible]);

  // Close on outside click
  useEffect(() => {
    if (!visible) return;
    const handler = (e: MouseEvent) => {
      if (
        triggerRef.current && !triggerRef.current.contains(e.target as Node) &&
        tooltipRef.current && !tooltipRef.current.contains(e.target as Node)
      ) {
        setVisible(false);
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [visible]);

  if (!resolvedBody) return <>{children}</>;

  return (
    <span
      ref={triggerRef}
      className={`relative inline-flex items-center gap-1 group ${className}`}
      onMouseEnter={() => setVisible(true)}
      onMouseLeave={() => setVisible(false)}
      onClick={(e) => { e.stopPropagation(); setVisible((v) => !v); }}
    >
      {children ?? (
        <HelpCircle className="w-3.5 h-3.5 text-gray-500 hover:text-cyan-400 cursor-help transition-colors flex-shrink-0" />
      )}

      {visible && (
        <div
          ref={tooltipRef}
          role="tooltip"
          className={`absolute z-50 w-72 bg-gray-800 border border-gray-700 rounded-lg shadow-lg p-3 text-left pointer-events-none
            ${position === 'top'
              ? 'bottom-full mb-2 left-1/2 -translate-x-1/2'
              : 'top-full mt-2 left-1/2 -translate-x-1/2'
            }`}
          onClick={(e) => e.stopPropagation()}
        >
          {/* Arrow */}
          <span
            className={`absolute left-1/2 -translate-x-1/2 w-0 h-0
              border-l-[6px] border-r-[6px] border-transparent
              ${position === 'top'
                ? 'top-full border-t-[6px] border-t-gray-700'
                : 'bottom-full border-b-[6px] border-b-gray-700'
              }`}
          />
          <p className="text-xs font-semibold text-cyan-300 mb-1">{resolvedTitle}</p>
          <p className="text-xs text-gray-300 leading-relaxed">{resolvedBody}</p>
        </div>
      )}
    </span>
  );
}

// ---------------------------------------------------------------------------
// Convenience: wrap a text node with an inline tooltip trigger
// ---------------------------------------------------------------------------

interface TermWithHelpProps {
  term: string;
  /** Displayed text — defaults to term if omitted */
  label?: string;
  className?: string;
}

/**
 * Renders `label` (or `term`) with a trailing help icon that shows
 * contextual information about the term on hover.
 */
export function TermWithHelp({ term, label, className = '' }: TermWithHelpProps) {
  return (
    <span className={`inline-flex items-center gap-1 ${className}`}>
      <span>{label ?? term}</span>
      <HelpTooltip term={term} />
    </span>
  );
}
