---
# Istio Ingress Gateway — north-south traffic entry point
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  interval: 10m
  dependsOn:
    - name: istiod
  chart:
    spec:
      chart: gateway
      version: "1.25.2"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
    # Istio gateway chart has strict JSON schema that rejects standard
    # values like 'resources' and 'service' at top level
    disableSchemaValidation: true
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    disableSchemaValidation: true
  values:
    replicaCount: 2
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
    service:
      type: NodePort
      ports:
        - name: status-port
          port: 15021
          protocol: TCP
          targetPort: 15021
        - name: http2
          port: 80
          protocol: TCP
          targetPort: 80
          nodePort: 31080
        - name: https
          port: 443
          protocol: TCP
          targetPort: 443
          nodePort: 31443
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    podDisruptionBudget:
      minAvailable: 1
