---
# Istio Base — CRDs and cluster-wide resources
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 10m
  chart:
    spec:
      chart: base
      version: "1.21.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultRevision: default
