---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "sre-cronjob.fullname" . }}
  labels:
    {{- include "sre-cronjob.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule.cron | quote }}
  {{- if .Values.schedule.timezone }}
  timeZone: {{ .Values.schedule.timezone | quote }}
  {{- end }}
  concurrencyPolicy: {{ .Values.schedule.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.schedule.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.schedule.failedJobsHistoryLimit }}
  startingDeadlineSeconds: {{ .Values.schedule.startingDeadlineSeconds }}
  jobTemplate:
    metadata:
      labels:
        {{- include "sre-cronjob.labels" . | nindent 8 }}
    spec:
      activeDeadlineSeconds: {{ .Values.schedule.activeDeadlineSeconds }}
      backoffLimit: {{ .Values.schedule.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "sre-cronjob.labels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ include "sre-cronjob.serviceAccountName" . }}
          automountServiceAccountToken: false
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          restartPolicy: {{ .Values.schedule.restartPolicy }}
          containers:
            - name: {{ .Values.app.name }}
              image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
              imagePullPolicy: {{ .Values.app.image.pullPolicy }}
              {{- with .Values.app.command }}
              command:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.app.args }}
              args:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                capabilities:
                  drop:
                    - ALL
              resources:
                requests:
                  cpu: {{ .Values.app.resources.requests.cpu }}
                  memory: {{ .Values.app.resources.requests.memory }}
                limits:
                  cpu: {{ .Values.app.resources.limits.cpu }}
                  memory: {{ .Values.app.resources.limits.memory }}
              env:
                {{- range .Values.app.env }}
                {{- if .value }}
                - name: {{ .name }}
                  value: {{ .value | quote }}
                {{- end }}
                {{- if .secretRef }}
                - name: {{ .name }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ .secretRef }}
                      key: value
                {{- end }}
                {{- end }}
