{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sre-worker.fullname" . }}
  labels:
    {{- include "sre-worker.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "sre-worker.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow Prometheus scraping from monitoring namespace
    {{- if .Values.serviceMonitor.enabled }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - port: {{ .Values.serviceMonitor.port }}
          protocol: TCP
    {{- end }}
  egress:
    # DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    # Allow traffic to same namespace
    - to:
        - podSelector: {}
    # Allow HTTPS egress (for external APIs, message queues)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 443
          protocol: TCP
    {{- with .Values.networkPolicy.additionalEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
