{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sre-worker.fullname" . }}-metrics
  labels:
    {{- include "sre-worker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.serviceMonitor.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "sre-worker.selectorLabels" . | nindent 4 }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sre-worker.fullname" . }}
  labels:
    {{- include "sre-worker.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sre-worker.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
