---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "72.6.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  dependsOn:
    - name: istio-base
      namespace: istio-system
    - name: kyverno
      namespace: kyverno
  install:
    crds: CreateReplace
    createNamespace: false
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    # ---------------------------------------------------------------
    # Prometheus
    # ---------------------------------------------------------------
    prometheus:
      enabled: true
      prometheusSpec:
        replicas: 2
        retention: "15d"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 2Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
        # Discover ServiceMonitors and PodMonitors across all namespaces
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        podMonitorSelector: {}
        ruleSelector: {}

    # ---------------------------------------------------------------
    # Grafana
    # ---------------------------------------------------------------
    grafana:
      enabled: true
      replicas: 2
      # Admin password injected via grafana-admin-credentials Secret (valuesFrom)
      # Do NOT set adminPassword inline — use bootstrap-secrets.sh
      service:
        type: ClusterIP
      persistence:
        enabled: true
        size: 10Gi
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      sidecar:
        dashboards:
          enabled: true
          searchNamespace: ALL
          label: "grafana_dashboard"
          folderAnnotation: "grafana_folder"
          provider:
            foldersFromFilesStructure: true
        datasources:
          enabled: true
          searchNamespace: ALL
          label: "grafana_datasource"
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki.logging.svc.cluster.local:3100
          access: proxy
          jsonData:
            maxLines: 1000
        - name: Tempo
          type: tempo
          url: http://tempo.tempo.svc.cluster.local:3100
          access: proxy
          jsonData:
            tracesToLogsV2:
              datasourceUid: loki
              enabled: true
            lokiSearch:
              datasourceUid: loki

    # ---------------------------------------------------------------
    # AlertManager
    # ---------------------------------------------------------------
    alertmanager:
      enabled: true
      alertmanagerSpec:
        replicas: 2
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        storage:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
      config:
        global:
          resolve_timeout: "5m"
        route:
          group_by:
            - "namespace"
            - "alertname"
          group_wait: "30s"
          group_interval: "5m"
          repeat_interval: "12h"
          receiver: "default-webhook"
          routes:
            - receiver: "critical-webhook"
              match:
                severity: "critical"
              repeat_interval: "1h"
        receivers:
          - name: "default-webhook"
            webhook_configs:
              - url: "http://REPLACE_ME:9095/webhook"
                send_resolved: true
          - name: "critical-webhook"
            webhook_configs:
              - url: "http://REPLACE_ME:9095/webhook"
                send_resolved: true

    # ---------------------------------------------------------------
    # Node Exporter
    # ---------------------------------------------------------------
    nodeExporter:
      enabled: true

    # ---------------------------------------------------------------
    # kube-state-metrics
    # ---------------------------------------------------------------
    kubeStateMetrics:
      enabled: true

    # ---------------------------------------------------------------
    # Disable components not available in RKE2 lab
    # ---------------------------------------------------------------
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: false

    # ---------------------------------------------------------------
    # Prometheus Operator
    # ---------------------------------------------------------------
    prometheusOperator:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 300m
          memory: 384Mi

    # ---------------------------------------------------------------
    # Default ServiceMonitor settings
    # ---------------------------------------------------------------
    defaultRules:
      create: true
      rules:
        alertmanager: true
        etcd: false
        configReloaders: true
        general: true
        k8s: true
        kubeApiserverAvailability: true
        kubeApiserverBurnrate: true
        kubeApiserverHistogram: true
        kubeApiserverSlos: true
        kubeControllerManager: true
        kubelet: true
        kubeProxy: false
        kubePrometheusGeneral: true
        kubePrometheusNodeRecording: true
        kubernetesApps: true
        kubernetesResources: true
        kubernetesStorage: true
        kubernetesSystem: true
        kubeSchedulerAlerting: true
        kubeSchedulerRecording: true
        kubeStateMetrics: true
        network: true
        node: true
        nodeExporterAlerting: true
        nodeExporterRecording: true
        prometheus: true
        prometheusOperator: true
  valuesFrom:
    - kind: Secret
      name: grafana-admin-credentials
      optional: true
    - kind: ConfigMap
      name: monitoring-env-values
      optional: true
