---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "57.2.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  dependsOn:
    - name: istio-base
      namespace: istio-system
    - name: kyverno
      namespace: kyverno
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # ---------------------------------------------------------------
    # Prometheus
    # ---------------------------------------------------------------
    prometheus:
      enabled: true
      prometheusSpec:
        replicas: 2
        retention: "15d"
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: "2"
            memory: 8Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
        # Discover ServiceMonitors and PodMonitors across all namespaces
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        podMonitorSelector: {}
        ruleSelector: {}

    # ---------------------------------------------------------------
    # Grafana
    # ---------------------------------------------------------------
    grafana:
      enabled: true
      replicas: 1
      admin:
        existingSecret: "grafana-admin-credentials"
        userKey: "admin-user"
        passwordKey: "admin-password"
      persistence:
        enabled: true
        size: 10Gi
      sidecar:
        dashboards:
          enabled: true
          searchNamespace: ALL
          label: "grafana_dashboard"
          folderAnnotation: "grafana_folder"
          provider:
            foldersFromFilesStructure: true
        datasources:
          enabled: true
          searchNamespace: ALL
          label: "grafana_datasource"
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi

    # ---------------------------------------------------------------
    # AlertManager
    # ---------------------------------------------------------------
    alertmanager:
      enabled: true
      alertmanagerSpec:
        replicas: 2
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      config:
        global:
          resolve_timeout: "5m"
        route:
          group_by:
            - "namespace"
            - "alertname"
          group_wait: "30s"
          group_interval: "5m"
          repeat_interval: "12h"
          receiver: "default-webhook"
          routes:
            - receiver: "critical-webhook"
              match:
                severity: "critical"
              repeat_interval: "1h"
        receivers:
          - name: "default-webhook"
            webhook_configs:
              - url: "http://REPLACE_ME:9095/webhook"
                send_resolved: true
          - name: "critical-webhook"
            webhook_configs:
              - url: "http://REPLACE_ME:9095/webhook"
                send_resolved: true

    # ---------------------------------------------------------------
    # Node Exporter
    # ---------------------------------------------------------------
    nodeExporter:
      enabled: true

    # ---------------------------------------------------------------
    # kube-state-metrics
    # ---------------------------------------------------------------
    kubeStateMetrics:
      enabled: true

    # ---------------------------------------------------------------
    # Default ServiceMonitor settings
    # ---------------------------------------------------------------
    defaultRules:
      create: true
      rules:
        alertmanager: true
        etcd: true
        configReloaders: true
        general: true
        k8s: true
        kubeApiserverAvailability: true
        kubeApiserverBurnrate: true
        kubeApiserverHistogram: true
        kubeApiserverSlos: true
        kubeControllerManager: true
        kubelet: true
        kubeProxy: true
        kubePrometheusGeneral: true
        kubePrometheusNodeRecording: true
        kubernetesApps: true
        kubernetesResources: true
        kubernetesStorage: true
        kubernetesSystem: true
        kubeSchedulerAlerting: true
        kubeSchedulerRecording: true
        kubeStateMetrics: true
        network: true
        node: true
        nodeExporterAlerting: true
        nodeExporterRecording: true
        prometheus: true
        prometheusOperator: true
  valuesFrom:
    - kind: ConfigMap
      name: monitoring-env-values
      optional: true
