---
extends: default

rules:
  line-length:
    max: 200
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
    check-keys: false
  indentation:
    spaces: 2
    indent-sequences: consistent
  empty-lines:
    max: 2
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

ignore: |
  .git/
  .claude/
  node_modules/
  infrastructure/tofu/.terraform/
  apps/templates/*/templates/
