---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-istio-security
  labels:
    app.kubernetes.io/part-of: sre-platform
rules:
  - apiGroups:
      - security.istio.io
    resources:
      - requestauthentications
      - authorizationpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-admission-controller-istio
  labels:
    app.kubernetes.io/part-of: sre-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-istio-security
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-background-controller-istio
  labels:
    app.kubernetes.io/part-of: sre-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-istio-security
subjects:
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno
