---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    app.kubernetes.io/part-of: sre-platform
    pod-security.kubernetes.io/enforce: privileged
    sre.io/system-namespace: "true"
    # Istio injection disabled for kyverno — webhook must work independently
