---
# Allow OpenBao pods to communicate with each other (Raft + API)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-openbao-cluster
  namespace: openbao
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: openbao
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Raft peering and API from other OpenBao pods
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: openbao
      ports:
        - port: 8200
          protocol: TCP
        - port: 8201
          protocol: TCP
    # API access from all namespaces (ESO, app pods via K8s auth)
    - from:
        - namespaceSelector: {}
      ports:
        - port: 8200
          protocol: TCP
    # Prometheus scraping
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - port: 8200
          protocol: TCP
  egress:
    # Raft peering with other OpenBao pods
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: openbao
      ports:
        - port: 8200
          protocol: TCP
        - port: 8201
          protocol: TCP
    # Kubernetes API (for K8s auth method and service registration)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 443
          protocol: TCP
        - port: 6443
          protocol: TCP
    # DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
