import React, { useState, useMemo } from 'react';
import { ArrowLeft, ArrowRight, ShieldAlert, FileCheck, Loader2, RotateCcw, Rocket, CheckCircle2, XCircle, RotateCw, AlertTriangle, Copy, Check, Tv2, LayoutList } from 'lucide-react';
import { Button } from '../ui/Button';
import { PipelineProgress } from '../pipeline/PipelineProgress';
import { GateCard } from '../pipeline/GateCard';
import { PipelineStream } from '../pipeline/PipelineStream';
import { TermWithHelp } from '../HelpTooltip';
import type { SecurityGate, GateFinding, PipelineRunStatus, PipelineRun } from '../../types';

interface Step4Props {
  gates: SecurityGate[];
  isPipelineRunning: boolean;
  onUpdateGate: (gateId: number, updates: Partial<SecurityGate>) => void;
  onUpdateFinding: (gateId: number, findingIndex: number, updates: Partial<GateFinding>) => void;
  onOverrideGate?: (gateId: number, status: 'passed' | 'skipped', reason: string) => void;
  isAdmin?: boolean;
  username: string;
  appName?: string;
  teamName?: string;
  onBack: () => void;
  onNext: () => void;
  pipelineRunId?: string | null;
  pipelineRunStatus?: PipelineRunStatus | null;
  pipelineRun?: PipelineRun | null;
  onSubmitForReview?: () => void;
  onRetryPipeline?: () => Promise<void>;
  exceptionJustification?: string;
  onExceptionJustificationChange?: (value: string) => void;
  onRequestException?: (pipelineRunId: string, exceptionType: string, justification: string) => void;
  exceptionRequested?: boolean;
  requestingException?: boolean;
}

interface DetectedException {
  type: string;
  reason: string;
}

function getDetectedExceptions(pipelineRun?: PipelineRun | null): DetectedException[] {
  if (!pipelineRun?.metadata?.detected_exceptions) return [];
  const raw = pipelineRun.metadata.detected_exceptions;
  if (!Array.isArray(raw)) return [];
  return raw as DetectedException[];
}

/** Map exception type to the Kyverno policy name it bypasses */
const exceptionTypeToPolicyName: Record<string, string> = {
  run_as_root: 'require-run-as-nonroot',
  writable_filesystem: 'require-security-context',
  host_networking: 'disallow-host-namespaces',
  privileged_container: 'disallow-privileged-containers',
  custom_capability: 'require-security-context',
};

const exceptionTypeToRuleName: Record<string, string> = {
  run_as_root: 'run-as-non-root',
  writable_filesystem: 'require-read-only-rootfs',
  host_networking: 'disallow-host-networking',
  privileged_container: 'disallow-privileged',
  custom_capability: 'drop-all-capabilities',
};

/** Generate a pre-filled PolicyException YAML from wizard context */
function generatePolicyExceptionYaml(
  appName: string,
  teamName: string,
  exceptionType: string,
  justification: string,
): string {
  const policyName = exceptionTypeToPolicyName[exceptionType] || 'POLICY-NAME';
  const ruleName = exceptionTypeToRuleName[exceptionType] || 'RULE-NAME';
  const expiryDate = new Date();
  expiryDate.setDate(expiryDate.getDate() + 90);
  const expiry = expiryDate.toISOString().split('T')[0];
  const safeName = `${teamName}-${appName}-${exceptionType}`.replace(/_/g, '-').toLowerCase();

  return `---
# PolicyException for ${appName} in ${teamName}
# Generated by DSOP Wizard — submit this as a PR for platform team review
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: ${safeName}
  namespace: ${teamName}
  labels:
    app.kubernetes.io/part-of: sre-platform
    sre.io/team: "${teamName}"
  annotations:
    sre.io/exception-reason: "${justification.replace(/"/g, '\\"')}"
    sre.io/exception-approver: "PENDING-REVIEW"
    sre.io/exception-expiry: "${expiry}"
    sre.io/ticket: "REPLACE-WITH-TICKET-URL"
spec:
  exceptions:
    - policyName: ${policyName}
      ruleNames:
        - ${ruleName}
  match:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - ${teamName}
          names:
            - "${appName}-*"
`;
}

function SecurityExceptionPrompt({
  pipelineRun,
  pipelineRunId,
  exceptionJustification = '',
  onExceptionJustificationChange,
  onRequestException,
  exceptionRequested = false,
  requestingException = false,
  appName = 'my-app',
  teamName = 'team-alpha',
}: {
  pipelineRun?: PipelineRun | null;
  pipelineRunId?: string | null;
  exceptionJustification?: string;
  onExceptionJustificationChange?: (value: string) => void;
  onRequestException?: (pipelineRunId: string, exceptionType: string, justification: string) => void;
  exceptionRequested?: boolean;
  requestingException?: boolean;
  appName?: string;
  teamName?: string;
}) {
  const [copied, setCopied] = useState(false);
  const detected = getDetectedExceptions(pipelineRun);
  if (detected.length === 0) return null;

  const generatedYaml = useMemo(() => {
    if (!exceptionRequested || detected.length === 0) return '';
    return generatePolicyExceptionYaml(
      appName,
      teamName,
      detected[0].type,
      exceptionJustification,
    );
  }, [exceptionRequested, detected, appName, teamName, exceptionJustification]);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generatedYaml);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = generatedYaml;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="bg-amber-900/30 border border-amber-500/50 rounded-lg p-4 mt-4">
      <h4 className="text-amber-400 font-semibold mb-2 flex items-center gap-2">
        <AlertTriangle className="w-4 h-4" />
        <TermWithHelp term="PolicyException" label="Security Exception Required" />
      </h4>
      <p className="text-sm text-gray-300 mb-3">
        This application requires elevated privileges that are normally restricted:
      </p>
      <ul className="list-disc list-inside text-sm text-gray-300 mb-3">
        {detected.map((ex, i) => (
          <li key={i}>
            {ex.reason} ({ex.type})
          </li>
        ))}
      </ul>
      {exceptionRequested ? (
        <div className="space-y-3">
          <div className="flex items-center gap-2 bg-emerald-500/10 border border-emerald-500/30 rounded-lg px-4 py-3">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            <span className="text-sm text-emerald-400">Security exception requested successfully</span>
          </div>
          {generatedYaml && (
            <div className="mt-3">
              <div className="flex items-center justify-between mb-2">
                <p className="text-sm text-gray-300 font-medium">
                  Copy this <TermWithHelp term="PolicyException" /> YAML into a PR at{' '}
                  <code className="text-cyan-400 text-xs">
                    policies/custom/policy-exceptions/{teamName}-{appName}-exception.yaml
                  </code>
                </p>
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1 text-xs text-gray-400 hover:text-cyan-400 transition-colors px-2 py-1 rounded border border-gray-600 hover:border-cyan-500"
                >
                  {copied ? (
                    <>
                      <Check className="w-3 h-3" />
                      Copied
                    </>
                  ) : (
                    <>
                      <Copy className="w-3 h-3" />
                      Copy YAML
                    </>
                  )}
                </button>
              </div>
              <pre className="bg-navy-900 border border-navy-600 rounded-lg p-4 text-xs text-gray-300 font-mono overflow-x-auto whitespace-pre max-h-64 overflow-y-auto">
                {generatedYaml}
              </pre>
              <p className="text-xs text-gray-500 mt-2">
                Full process: see policies/custom/policy-exceptions/README.md
              </p>
            </div>
          )}
        </div>
      ) : (
        <>
          <textarea
            placeholder="Provide justification for why this exception is needed..."
            className="w-full bg-navy-800 border border-gray-600 rounded p-2 text-sm text-white mb-2 placeholder-gray-500 focus:border-amber-500 focus:outline-none"
            value={exceptionJustification}
            onChange={(e) => onExceptionJustificationChange?.(e.target.value)}
            rows={3}
          />
          <button
            className="bg-amber-600 hover:bg-amber-500 disabled:bg-amber-800 disabled:cursor-not-allowed text-white px-4 py-2 rounded text-sm flex items-center gap-2"
            onClick={() => {
              if (pipelineRunId && onRequestException) {
                onRequestException(pipelineRunId, detected[0].type, exceptionJustification);
              }
            }}
            disabled={requestingException || !exceptionJustification.trim()}
          >
            {requestingException ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Requesting...
              </>
            ) : (
              'Request Security Exception'
            )}
          </button>
        </>
      )}
    </div>
  );
}

export function Step4_SecurityPipeline({
  gates,
  isPipelineRunning,
  onUpdateGate,
  onUpdateFinding,
  onOverrideGate,
  isAdmin,
  username,
  appName = 'my-app',
  teamName = 'team-alpha',
  onBack,
  onNext,
  pipelineRunId,
  pipelineRunStatus,
  pipelineRun,
  onSubmitForReview,
  onRetryPipeline,
  exceptionJustification = '',
  onExceptionJustificationChange,
  onRequestException,
  exceptionRequested = false,
  requestingException = false,
}: Step4Props) {
  const [submittingReview, setSubmittingReview] = useState(false);
  const [retrying, setRetrying] = useState(false);
  const [showLiveFeed, setShowLiveFeed] = useState(false);

  // Automated gates = everything except ISSM_REVIEW and IMAGE_SIGNING
  const automatedGates = gates.filter(
    (g) => g.shortName !== 'ISSM REVIEW' && g.shortName !== 'ISSM_REVIEW' &&
           g.shortName !== 'IMAGE SIGNING' && g.shortName !== 'IMAGE_SIGNING'
  );

  const automatedDone = automatedGates.every(
    (g) => g.status !== 'pending' && g.status !== 'running'
  );
  const automatedPassed = automatedGates.every(
    (g) => g.status === 'passed' || g.status === 'warning' || g.status === 'skipped'
  );
  const hasCriticalFailure = automatedGates.some((g) => g.status === 'failed');

  const isReviewPending = pipelineRunStatus === 'review_pending';
  const isApproved = pipelineRunStatus === 'approved';
  const isDeploying = pipelineRunStatus === 'deploying';
  const isDeployed = pipelineRunStatus === 'deployed';
  const isRejected = pipelineRunStatus === 'rejected';
  const isReturned = pipelineRunStatus === 'returned';
  const isFailed = pipelineRunStatus === 'failed';

  const canSubmitForReview =
    pipelineRunId &&
    onSubmitForReview &&
    automatedDone &&
    !isReviewPending &&
    !isApproved;

  // User can proceed once automated gates are done — failures go to ISSM for waiver
  const canProceed = automatedDone;

  const handleSubmitForReview = async () => {
    if (!onSubmitForReview) return;
    setSubmittingReview(true);
    try {
      await onSubmitForReview();
    } finally {
      setSubmittingReview(false);
    }
  };

  const handleAcknowledge = (gateId: number) => {
    const gate = gates.find((g) => g.id === gateId);
    if (gate) {
      onUpdateGate(gateId, { manualAck: !gate.manualAck });
    }
  };

  const [linkCopied, setLinkCopied] = useState(false);

  const handleCopyLink = () => {
    if (!pipelineRunId) return;
    try {
      const url = new URL(window.location.href);
      url.searchParams.set('runId', pipelineRunId);
      // Remove transient params
      url.searchParams.delete('new');
      url.searchParams.delete('theme');
      navigator.clipboard.writeText(url.toString()).then(() => {
        setLinkCopied(true);
        setTimeout(() => setLinkCopied(false), 2000);
      });
    } catch {
      // Ignore clipboard failures
    }
  };

  return (
    <div className="space-y-6">
      {/* Pipeline Progress Header */}
      <div className="flex items-center justify-between">
        <PipelineProgress gates={gates} />
        {pipelineRunId && (
          <button
            onClick={handleCopyLink}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border border-navy-600 bg-navy-800 text-gray-300 hover:border-cyan-500/40 hover:text-cyan-400 transition-all shrink-0 ml-4"
            title="Copy shareable link to this pipeline run"
          >
            {linkCopied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            {linkCopied ? 'Copied' : 'Copy Link'}
          </button>
        )}
      </div>

      {/* View toggle (only shown when a pipeline run is active or recently completed) */}
      {pipelineRunId && (
        <div className="flex items-center gap-3">
          <div className="flex rounded-lg border border-navy-600 overflow-hidden text-xs font-medium shadow-sm">
            <button
              onClick={() => setShowLiveFeed(false)}
              className={`flex items-center gap-1.5 px-4 py-2 transition-colors ${
                !showLiveFeed
                  ? 'bg-navy-600 text-white'
                  : 'bg-navy-800 text-gray-400 hover:text-gray-200 hover:bg-navy-700'
              }`}
            >
              <LayoutList className="w-3.5 h-3.5" />
              Gate Cards
            </button>
            <button
              onClick={() => setShowLiveFeed(true)}
              className={`flex items-center gap-1.5 px-4 py-2 transition-colors ${
                showLiveFeed
                  ? 'bg-cyan-600 text-white'
                  : 'bg-navy-800 text-cyan-400 hover:text-cyan-300 hover:bg-navy-700'
              }`}
            >
              <Tv2 className="w-3.5 h-3.5" />
              Live Feed
              {isPipelineRunning && (
                <span className="relative flex h-2 w-2 ml-0.5">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-cyan-400 opacity-75" />
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-cyan-500" />
                </span>
              )}
            </button>
          </div>
          {isPipelineRunning && !showLiveFeed && (
            <span className="text-xs text-cyan-400 animate-pulse">
              Pipeline running — switch to Live Feed for real-time logs
            </span>
          )}
        </div>
      )}

      {/* Gate Cards — expand inline, no modal */}
      {!showLiveFeed && (
        <div className="space-y-3">
          {gates.map((gate) => (
            <GateCard
              key={gate.id}
              gate={gate}
              pipelineRunId={pipelineRunId}
              onAcknowledge={handleAcknowledge}
              onUpdateFinding={onUpdateFinding}
              onOverrideGate={onOverrideGate}
              isAdmin={isAdmin}
              username={username}
            />
          ))}
        </div>
      )}

      {/* Live Feed — SSE stream view */}
      {showLiveFeed && (
        <PipelineStream runId={pipelineRunId} gates={gates} />
      )}

      {/* Security Exception Prompt */}
      <SecurityExceptionPrompt
        pipelineRun={pipelineRun}
        pipelineRunId={pipelineRunId}
        exceptionJustification={exceptionJustification}
        onExceptionJustificationChange={onExceptionJustificationChange}
        onRequestException={onRequestException}
        exceptionRequested={exceptionRequested}
        requestingException={requestingException}
        appName={appName}
        teamName={teamName}
      />

      {/* Status Messages */}
      {hasCriticalFailure && (
        <div className="bg-amber-500/10 border border-amber-500/30 rounded-xl p-4 text-center space-y-3">
          <p className="text-sm text-amber-400">
            One or more security gates have findings. Submit to ISSM for review — all findings can be waivered with justification.
          </p>
          {onRetryPipeline && pipelineRunId && (
            <Button
              variant="secondary"
              onClick={async () => {
                setRetrying(true);
                try { await onRetryPipeline(); } finally { setRetrying(false); }
              }}
              disabled={retrying}
              icon={retrying ? <Loader2 className="w-4 h-4 animate-spin" /> : <RotateCcw className="w-4 h-4" />}
            >
              {retrying ? 'Restarting...' : 'Restart Pipeline'}
            </Button>
          )}
        </div>
      )}

      {/* ISSM Review Submission */}
      {automatedDone && (
        <div className="bg-navy-800 border border-navy-600 rounded-xl p-5 space-y-3">
          <h3 className="text-sm font-semibold text-gray-400 uppercase tracking-wider flex items-center gap-2">
            <FileCheck className="w-4 h-4" />
            <TermWithHelp term="ISSM" label="ISSM Review" />
          </h3>
          {isDeployed ? (
            <div className="flex items-center gap-2 bg-emerald-500/10 border border-emerald-500/30 rounded-lg px-4 py-3">
              <CheckCircle2 className="w-5 h-5 text-emerald-400" />
              <span className="text-sm text-emerald-400 font-medium">
                ISSM Review: Approved — Application deployed
              </span>
            </div>
          ) : isDeploying ? (
            <div className="flex items-center gap-2 bg-cyan-500/10 border border-cyan-500/30 rounded-lg px-4 py-3">
              <Loader2 className="w-5 h-5 text-cyan-400 animate-spin" />
              <span className="text-sm text-cyan-400 font-medium">
                ISSM Review: Approved — Deploying to cluster...
              </span>
            </div>
          ) : isApproved ? (
            <div className="flex items-center gap-2 bg-emerald-500/10 border border-emerald-500/30 rounded-lg px-4 py-3">
              <ShieldAlert className="w-5 h-5 text-emerald-400" />
              <span className="text-sm text-emerald-400 font-medium">
                ISSM Review: Approved — ready to deploy
              </span>
            </div>
          ) : isReviewPending ? (
            <div className="flex items-center gap-2 bg-cyan-500/10 border border-cyan-500/30 rounded-lg px-4 py-3">
              <Loader2 className="w-5 h-5 text-cyan-400 animate-spin" />
              <span className="text-sm text-cyan-400">
                Submitted for ISSM review — awaiting decision...
              </span>
            </div>
          ) : canSubmitForReview ? (
            <div className="space-y-2">
              <p className="text-sm text-gray-300">
                All automated security gates have completed. Submit this pipeline run for ISSM review to proceed with deployment.
              </p>
              <Button
                onClick={handleSubmitForReview}
                disabled={submittingReview}
                icon={submittingReview ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileCheck className="w-4 h-4" />}
              >
                {submittingReview ? 'Submitting...' : 'Submit for ISSM Review'}
              </Button>
            </div>
          ) : !pipelineRunId ? (
            <p className="text-sm text-gray-400">
              Complete the automated security gates above, then submit for ISSM review.
            </p>
          ) : null}
        </div>
      )}

      {/* Pipeline Status Transitions */}
      {isRejected && (
        <div className="bg-red-500/10 border border-red-500/30 rounded-xl p-5 space-y-3">
          <div className="flex items-center gap-2">
            <XCircle className="w-5 h-5 text-red-400" />
            <span className="text-sm text-red-400 font-medium">
              ISSM Review: Rejected
            </span>
          </div>
          <p className="text-xs text-gray-400">
            The ISSM has rejected this pipeline run. Please address the findings and resubmit.
          </p>
          {onRetryPipeline && pipelineRunId && (
            <Button
              variant="secondary"
              onClick={async () => {
                setRetrying(true);
                try { await onRetryPipeline(); } finally { setRetrying(false); }
              }}
              disabled={retrying}
              icon={retrying ? <Loader2 className="w-4 h-4 animate-spin" /> : <RotateCcw className="w-4 h-4" />}
            >
              {retrying ? 'Restarting...' : 'Restart Pipeline'}
            </Button>
          )}
        </div>
      )}

      {isReturned && (
        <div className="bg-amber-500/10 border border-amber-500/30 rounded-xl p-5 space-y-3">
          <div className="flex items-center gap-2">
            <RotateCw className="w-5 h-5 text-amber-400" />
            <span className="text-sm text-amber-400 font-medium">
              ISSM Review: Returned for Revision
            </span>
          </div>
          <p className="text-xs text-gray-400">
            The ISSM has returned this pipeline run for revisions. Please address the feedback and resubmit.
          </p>
        </div>
      )}

      {isDeploying && (
        <div className="bg-cyan-500/10 border border-cyan-500/30 rounded-xl p-5">
          <div className="flex items-center gap-2">
            <Loader2 className="w-5 h-5 text-cyan-400 animate-spin" />
            <span className="text-sm text-cyan-400 font-medium">
              Deploying to cluster...
            </span>
          </div>
          <p className="text-xs text-gray-400 mt-2">
            Your application is being deployed to the SRE platform. This page will update automatically.
          </p>
        </div>
      )}

      {isDeployed && (
        <div className="bg-emerald-500/10 border border-emerald-500/30 rounded-xl p-5">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-5 h-5 text-emerald-400" />
            <span className="text-sm text-emerald-400 font-medium">
              Deployed successfully!
            </span>
          </div>
          <p className="text-xs text-gray-400 mt-2">
            Your application is live on the SRE platform.
          </p>
        </div>
      )}

      {isFailed && !hasCriticalFailure && (
        <div className="bg-red-500/10 border border-red-500/30 rounded-xl p-5 space-y-3">
          <div className="flex items-center gap-2">
            <XCircle className="w-5 h-5 text-red-400" />
            <span className="text-sm text-red-400 font-medium">
              Pipeline failed
            </span>
          </div>
          <p className="text-xs text-gray-400">
            The pipeline run has failed. Please check the gate results above for details.
          </p>
          {onRetryPipeline && pipelineRunId && (
            <Button
              variant="secondary"
              onClick={async () => {
                setRetrying(true);
                try { await onRetryPipeline(); } finally { setRetrying(false); }
              }}
              disabled={retrying}
              icon={retrying ? <Loader2 className="w-4 h-4 animate-spin" /> : <RotateCcw className="w-4 h-4" />}
            >
              {retrying ? 'Restarting...' : 'Restart Pipeline'}
            </Button>
          )}
        </div>
      )}

      {/* Navigation */}
      <div className="flex justify-between">
        <Button
          variant="secondary"
          onClick={onBack}
          disabled={isPipelineRunning || isDeploying}
          icon={<ArrowLeft className="w-4 h-4" />}
        >
          Back
        </Button>
        <Button
          onClick={onNext}
          disabled={!canProceed || isPipelineRunning || isDeploying}
          icon={<ArrowRight className="w-4 h-4" />}
          size="lg"
        >
          Continue to Review
        </Button>
      </div>
    </div>
  );
}
