---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: memos
  namespace: team-demo
  labels:
    app.kubernetes.io/part-of: sre-platform
    sre.io/team: team-demo
spec:
  interval: 10m
  chart:
    spec:
      chart: ./apps/templates/web-app
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    imagePullSecrets:
      - name: harbor-pull-creds
    app:
      name: memos
      team: team-demo
      image:
        repository: harbor.apps.sre.example.com/team-demo/memos
        tag: '1.0'
        pullPolicy: IfNotPresent
      port: 5230
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
      probes:
        liveness:
          path: /
          initialDelaySeconds: 10
          periodSeconds: 10
        readiness:
          path: /
          initialDelaySeconds: 5
          periodSeconds: 5
      env: []
    ingress:
      enabled: true
      host: memos.apps.sre.example.com
    autoscaling:
      enabled: false
    serviceMonitor:
      enabled: false
    networkPolicy:
      enabled: true
    podDisruptionBudget:
      enabled: false
    podSecurityContext:
      runAsNonRoot: false
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      runAsNonRoot: false
      runAsUser: 0
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      capabilities:
        drop:
          - ALL
        add:
          - CHOWN
          - FOWNER
          - SETGID
          - SETUID
          - DAC_OVERRIDE
    startupProbe:
      enabled: true
      path: /
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 30
    persistence:
      enabled: true
      mountPath: /var/lib/memos
      size: 10Gi
