---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    istio-injection: enabled
    app.kubernetes.io/part-of: sre-platform
    pod-security.kubernetes.io/enforce: privileged
