---
# Flux Kustomization for Keycloak identity provider
# Depends on: istio, cert-manager, openbao, monitoring
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sre-keycloak
  namespace: flux-system
  annotations:
    sre.io/nist-controls: "AC-2, AC-14, AC-17, IA-2, IA-5, IA-8"
spec:
  interval: 10m
  path: ./platform/addons/keycloak
  prune: true
  sourceRef:
    kind: GitRepository
    name: sre-platform
  dependsOn:
    - name: sre-istio
    - name: sre-cert-manager
    - name: sre-openbao
    - name: sre-monitoring
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: keycloak
      namespace: keycloak
  timeout: 10m
