import type { AppSource, DetectionResult, SecurityGate, DeployStep } from './types';

const API_BASE = '/api';

async function apiFetch<T>(path: string, options?: RequestInit): Promise<T> {
  const res = await fetch(`${API_BASE}${path}`, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new Error(`API ${res.status}: ${body || res.statusText}`);
  }
  return res.json();
}

export async function checkHealth(): Promise<{ status: string }> {
  return apiFetch('/health');
}

export async function getTeams(): Promise<string[]> {
  try {
    const data = await apiFetch<{ namespaces?: string[] }>('/portal/apps');
    return data.namespaces || ['team-alpha', 'team-bravo', 'team-charlie', 'default'];
  } catch {
    return ['team-alpha', 'team-bravo', 'team-charlie', 'default'];
  }
}

export async function analyzeSource(source: AppSource): Promise<DetectionResult> {
  try {
    if (source.type === 'git' && source.gitUrl) {
      const data = await apiFetch<DetectionResult>('/deploy/git', {
        method: 'POST',
        body: JSON.stringify({
          url: source.gitUrl,
          branch: source.branch || 'main',
          analyze_only: true,
        }),
      });
      return data;
    }
  } catch {
    // Fall through to mock
  }

  // Realistic mock detection for demo
  await simulateDelay(2500);

  if (source.type === 'container') {
    return {
      repoType: 'container',
      services: [
        { name: 'app', image: source.imageUrl || 'nginx:latest', port: 8080, type: 'application' },
      ],
      platformServices: [],
      externalAccess: [
        { service: 'app', hostname: 'app.apps.sre.example.com' },
      ],
    };
  }

  if (source.type === 'helm') {
    return {
      repoType: 'helm',
      services: [
        { name: source.chartName || 'app', image: 'chart-managed', port: 8080, type: 'application' },
      ],
      platformServices: [],
      externalAccess: [
        { service: source.chartName || 'app', hostname: `${source.chartName || 'app'}.apps.sre.example.com` },
      ],
    };
  }

  // Git repo mock
  return {
    repoType: 'docker-compose',
    services: [
      { name: 'frontend', image: 'nginx:1.27', port: 80, type: 'application' },
      { name: 'backend', image: 'python:3.11', port: 8000, type: 'application' },
      { name: 'worker', image: 'python:3.11', port: null, type: 'application' },
    ],
    platformServices: [
      { detected: 'PostgreSQL', mappedTo: 'CNPG Cluster', icon: 'database' },
      { detected: 'Redis', mappedTo: 'In-cluster Redis', icon: 'zap' },
    ],
    externalAccess: [
      { service: 'frontend', hostname: 'app.apps.sre.example.com' },
    ],
  };
}

export function getInitialGates(): SecurityGate[] {
  return [
    {
      id: 1,
      name: 'Static Application Security Testing (SAST)',
      shortName: 'SAST',
      description: 'Semgrep scans source code for vulnerabilities, insecure patterns, and CWE violations.',
      status: 'pending',
      progress: 0,
      findings: [],
      implemented: false,
    },
    {
      id: 2,
      name: 'Software Bill of Materials (SBOM)',
      shortName: 'SBOM',
      description: 'Syft generates SPDX and CycloneDX SBOMs for all container images. Harbor auto-generates on push.',
      status: 'pending',
      progress: 0,
      findings: [],
      implemented: true,
      summary: 'SBOM auto-generated by Harbor (Syft)',
    },
    {
      id: 3,
      name: 'Secrets Detection',
      shortName: 'SECRETS',
      description: 'Gitleaks scans repository history and current code for leaked credentials, API keys, and tokens.',
      status: 'pending',
      progress: 0,
      findings: [],
      implemented: true,
    },
    {
      id: 4,
      name: 'CVE / Vulnerability Scan',
      shortName: 'CVE SCAN',
      description: 'Trivy scans container images for known CVEs against the NVD and vendor advisories.',
      status: 'pending',
      progress: 0,
      findings: [],
      implemented: true,
    },
    {
      id: 5,
      name: 'Dynamic Application Security Testing (DAST)',
      shortName: 'DAST',
      description: 'ZAP or Nuclei scans the running application for OWASP Top 10 vulnerabilities.',
      status: 'pending',
      progress: 0,
      findings: [],
      implemented: false,
    },
    {
      id: 6,
      name: 'ISSM / Security Review',
      shortName: 'ISSM REVIEW',
      description: 'Information System Security Manager reviews scan results and approves for deployment.',
      status: 'pending',
      progress: 0,
      findings: [],
      implemented: false,
    },
    {
      id: 7,
      name: 'Container Image Signing',
      shortName: 'IMAGE SIGNING',
      description: 'Cosign signs container images with a keyless or key-based signature for supply chain integrity.',
      status: 'pending',
      progress: 0,
      findings: [],
      implemented: false,
    },
    {
      id: 8,
      name: 'Artifact Storage & Registry',
      shortName: 'ARTIFACT STORE',
      description: 'Harbor stores signed images, SBOMs, and vulnerability reports in the enterprise registry.',
      status: 'pending',
      progress: 0,
      findings: [],
      implemented: true,
      summary: 'Harbor: Images stored and scanned',
    },
  ];
}

export async function runSecurityPipeline(
  gates: SecurityGate[],
  onUpdate: (gates: SecurityGate[]) => void
): Promise<SecurityGate[]> {
  const updated = [...gates.map((g) => ({ ...g }))];

  // Gate 3: Secrets Detection - runs first
  updated[2] = { ...updated[2], status: 'running', progress: 0 };
  onUpdate([...updated]);
  await simulateProgress(updated, 2, onUpdate, 1800);
  updated[2] = {
    ...updated[2],
    status: 'passed',
    progress: 100,
    summary: 'Gitleaks: 0 secrets detected',
    findings: [],
  };
  onUpdate([...updated]);

  // Gate 8: Artifact Store - quick
  updated[7] = { ...updated[7], status: 'running', progress: 0 };
  onUpdate([...updated]);
  await simulateDelay(800);
  updated[7] = {
    ...updated[7],
    status: 'passed',
    progress: 100,
    summary: 'Harbor: Images pushed and stored',
    reportUrl: 'https://harbor.apps.sre.example.com',
  };
  onUpdate([...updated]);

  // Gate 2: SBOM - auto by Harbor
  updated[1] = { ...updated[1], status: 'running', progress: 0 };
  onUpdate([...updated]);
  await simulateProgress(updated, 1, onUpdate, 2000);
  updated[1] = {
    ...updated[1],
    status: 'passed',
    progress: 100,
    summary: 'SBOM auto-generated by Harbor (SPDX + CycloneDX)',
  };
  onUpdate([...updated]);

  // Gate 4: CVE Scan - Trivy
  updated[3] = { ...updated[3], status: 'running', progress: 0 };
  onUpdate([...updated]);
  await simulateProgress(updated, 3, onUpdate, 3500);
  updated[3] = {
    ...updated[3],
    status: 'warning',
    progress: 100,
    summary: 'Trivy: 0 critical, 2 high, 5 medium, 12 low',
    findings: [
      {
        severity: 'high',
        title: 'CVE-2024-6387 - OpenSSH regresshion',
        description: 'Signal handler race condition in OpenSSH sshd allows unauthenticated remote code execution.',
        location: 'openssh-server 9.6p1',
      },
      {
        severity: 'high',
        title: 'CVE-2024-3094 - xz utils backdoor',
        description: 'Malicious code in xz/liblzma allows unauthorized access via sshd.',
        location: 'xz-utils 5.6.0',
      },
      {
        severity: 'medium',
        title: 'CVE-2024-2961 - glibc iconv overflow',
        description: 'Buffer overflow in glibc iconv when converting to ISO-2022-CN-EXT.',
        location: 'glibc 2.38',
      },
      {
        severity: 'medium',
        title: 'CVE-2024-0567 - GnuTLS verification bypass',
        description: 'Timing side-channel in GnuTLS RSA-PSK key exchange allows certificate verification bypass.',
        location: 'gnutls 3.8.2',
      },
      {
        severity: 'medium',
        title: 'CVE-2023-50387 - DNSSEC KeyTrap',
        description: 'DNS resolution CPU exhaustion via crafted DNSSEC responses.',
        location: 'systemd-resolved 254',
      },
    ],
    reportUrl: 'https://harbor.apps.sre.example.com/projects/1/repositories',
  };
  onUpdate([...updated]);

  // Gate 1: SAST - not implemented
  updated[0] = {
    ...updated[0],
    status: 'skipped',
    progress: 100,
    summary: 'Coming Soon \u2014 Manual Verification Required',
  };
  onUpdate([...updated]);

  // Gate 5: DAST - not implemented
  updated[4] = {
    ...updated[4],
    status: 'skipped',
    progress: 100,
    summary: 'Coming Soon \u2014 Runs after staging deploy',
  };
  onUpdate([...updated]);

  // Gate 6: ISSM Review - not implemented
  updated[5] = {
    ...updated[5],
    status: 'skipped',
    progress: 100,
    summary: 'Coming Soon \u2014 Manual ISSM Approval Required',
  };
  onUpdate([...updated]);

  // Gate 7: Image Signing - not implemented
  updated[6] = {
    ...updated[6],
    status: 'skipped',
    progress: 100,
    summary: 'Coming Soon \u2014 Cosign integration pending',
  };
  onUpdate([...updated]);

  return updated;
}

export function getInitialDeploySteps(): DeployStep[] {
  return [
    { id: 'namespace', label: 'Namespace created', status: 'pending' },
    { id: 'pull-secret', label: 'Harbor pull secret configured', status: 'pending' },
    { id: 'helm-release', label: 'HelmRelease created', status: 'pending' },
    { id: 'pods', label: 'Pods starting', status: 'pending' },
    { id: 'health', label: 'Health check', status: 'pending' },
    { id: 'portal', label: 'Portal registration', status: 'pending' },
  ];
}

export async function runDeploy(
  appName: string,
  steps: DeployStep[],
  onUpdate: (steps: DeployStep[]) => void
): Promise<{ url: string; steps: DeployStep[] }> {
  const updated = [...steps.map((s) => ({ ...s }))];

  for (let i = 0; i < updated.length; i++) {
    updated[i] = { ...updated[i], status: 'running' };
    onUpdate([...updated]);
    await simulateDelay(1200 + Math.random() * 800);
    updated[i] = { ...updated[i], status: 'completed' };
    onUpdate([...updated]);
  }

  const url = `https://${appName}.apps.sre.example.com`;
  return { url, steps: updated };
}

// Helpers

function simulateDelay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function simulateProgress(
  gates: SecurityGate[],
  index: number,
  onUpdate: (gates: SecurityGate[]) => void,
  totalMs: number
): Promise<void> {
  const steps = 10;
  const interval = totalMs / steps;
  for (let i = 1; i <= steps; i++) {
    await simulateDelay(interval);
    gates[index] = { ...gates[index], progress: i * 10 };
    onUpdate([...gates]);
  }
}
