import type { AppSource, DetectionResult, SecurityGate, DeployStep } from './types';

const API_BASE = '/api';

async function apiFetch<T>(path: string, options?: RequestInit): Promise<T> {
  const res = await fetch(`${API_BASE}${path}`, {
    ...options,
    credentials: 'include',
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new Error(`API ${res.status}: ${body || res.statusText}`);
  }
  return res.json();
}

export async function checkHealth(): Promise<{ status: string }> {
  return apiFetch('/health');
}

export async function getTeams(): Promise<string[]> {
  try {
    const data = await apiFetch<{ namespaces?: string[] }>('/portal/apps');
    return data.namespaces || ['team-alpha', 'team-bravo', 'team-charlie', 'default'];
  } catch {
    return ['team-alpha', 'team-bravo', 'team-charlie', 'default'];
  }
}

export async function analyzeSource(source: AppSource): Promise<DetectionResult> {
  try {
    if (source.type === 'git' && source.gitUrl) {
      const data = await apiFetch<DetectionResult>('/deploy/git', {
        method: 'POST',
        body: JSON.stringify({
          url: source.gitUrl,
          branch: source.branch || 'main',
          analyze_only: true,
        }),
      });
      return data;
    }
  } catch {
    // Fall through to mock
  }

  // Realistic mock detection for demo
  await simulateDelay(2500);

  if (source.type === 'container') {
    return {
      repoType: 'container',
      services: [
        { name: 'app', image: source.imageUrl || 'nginx:latest', port: 8080, type: 'application' },
      ],
      platformServices: [],
      externalAccess: [
        { service: 'app', hostname: 'app.apps.sre.example.com' },
      ],
    };
  }

  if (source.type === 'helm') {
    return {
      repoType: 'helm',
      services: [
        { name: source.chartName || 'app', image: 'chart-managed', port: 8080, type: 'application' },
      ],
      platformServices: [],
      externalAccess: [
        { service: source.chartName || 'app', hostname: `${source.chartName || 'app'}.apps.sre.example.com` },
      ],
    };
  }

  // Git repo mock
  return {
    repoType: 'docker-compose',
    services: [
      { name: 'frontend', image: 'nginx:1.27', port: 80, type: 'application' },
      { name: 'backend', image: 'python:3.11', port: 8000, type: 'application' },
      { name: 'worker', image: 'python:3.11', port: null, type: 'application' },
    ],
    platformServices: [
      { detected: 'PostgreSQL', mappedTo: 'CNPG Cluster', icon: 'database' },
      { detected: 'Redis', mappedTo: 'In-cluster Redis', icon: 'zap' },
    ],
    externalAccess: [
      { service: 'frontend', hostname: 'app.apps.sre.example.com' },
    ],
  };
}

export function getInitialGates(): SecurityGate[] {
  return [
    {
      id: 1,
      name: 'Static Application Security Testing (SAST)',
      shortName: 'SAST',
      description: 'Semgrep scans source code for vulnerabilities, insecure patterns, and CWE violations.',
      status: 'pending',
      progress: 0,
      findings: [],
      implemented: false,
    },
    {
      id: 2,
      name: 'Software Bill of Materials (SBOM)',
      shortName: 'SBOM',
      description: 'Syft generates SPDX and CycloneDX SBOMs for all container images. Harbor auto-generates on push.',
      status: 'pending',
      progress: 0,
      findings: [],
      implemented: true,
      summary: 'SBOM auto-generated by Harbor (Syft)',
    },
    {
      id: 3,
      name: 'Secrets Detection',
      shortName: 'SECRETS',
      description: 'Gitleaks scans repository history and current code for leaked credentials, API keys, and tokens.',
      status: 'pending',
      progress: 0,
      findings: [],
      implemented: true,
    },
    {
      id: 4,
      name: 'CVE / Vulnerability Scan',
      shortName: 'CVE SCAN',
      description: 'Trivy scans container images for known CVEs against the NVD and vendor advisories.',
      status: 'pending',
      progress: 0,
      findings: [],
      implemented: true,
    },
    {
      id: 5,
      name: 'Dynamic Application Security Testing (DAST)',
      shortName: 'DAST',
      description: 'ZAP or Nuclei scans the running application for OWASP Top 10 vulnerabilities.',
      status: 'pending',
      progress: 0,
      findings: [],
      implemented: false,
    },
    {
      id: 6,
      name: 'ISSM / Security Review',
      shortName: 'ISSM REVIEW',
      description: 'Information System Security Manager reviews scan results and approves for deployment.',
      status: 'pending',
      progress: 0,
      findings: [],
      implemented: false,
    },
    {
      id: 7,
      name: 'Container Image Signing',
      shortName: 'IMAGE SIGNING',
      description: 'Cosign signs container images with a keyless or key-based signature for supply chain integrity.',
      status: 'pending',
      progress: 0,
      findings: [],
      implemented: false,
    },
    {
      id: 8,
      name: 'Artifact Storage & Registry',
      shortName: 'ARTIFACT STORE',
      description: 'Harbor stores signed images, SBOMs, and vulnerability reports in the enterprise registry.',
      status: 'pending',
      progress: 0,
      findings: [],
      implemented: true,
      summary: 'Harbor: Images stored and scanned',
    },
  ];
}

export async function runSecurityPipeline(
  gates: SecurityGate[],
  onUpdate: (gates: SecurityGate[]) => void,
  gitUrl?: string,
  branch?: string
): Promise<SecurityGate[]> {
  const updated = [...gates.map((g) => ({ ...g }))];
  const repoUrl = gitUrl || '';
  const repoBranch = branch || 'main';

  // Helper to run a real gate via backend API
  async function runGate(
    idx: number,
    endpoint: string,
    body: Record<string, string>,
    fallbackStatus: SecurityGate['status'],
    fallbackSummary: string
  ) {
    updated[idx] = { ...updated[idx], status: 'running', progress: 0 };
    onUpdate([...updated]);

    // Animate progress while waiting
    const progressInterval = setInterval(() => {
      if (updated[idx].progress < 90) {
        updated[idx] = { ...updated[idx], progress: updated[idx].progress + 5 };
        onUpdate([...updated]);
      }
    }, 500);

    try {
      const result = await apiFetch<{
        status: string;
        findings?: Array<{ severity: string; title: string; description: string; location?: string }>;
        summary: string;
        reportUrl?: string;
        packageCount?: number;
      }>(endpoint, { method: 'POST', body: JSON.stringify(body) });

      clearInterval(progressInterval);
      updated[idx] = {
        ...updated[idx],
        status: (result.status as SecurityGate['status']) || 'passed',
        progress: 100,
        summary: result.summary || fallbackSummary,
        findings: (result.findings || []).map(f => ({ ...f, severity: (f.severity?.toLowerCase() || 'info') as 'critical' | 'high' | 'medium' | 'low' | 'info' })),
        reportUrl: result.reportUrl,
        implemented: true,
      };
    } catch (err) {
      clearInterval(progressInterval);
      // Fallback: show mock results if backend unavailable
      updated[idx] = {
        ...updated[idx],
        status: fallbackStatus,
        progress: 100,
        summary: `${fallbackSummary} (API unavailable — using demo data)`,
        implemented: true,
      };
    }
    onUpdate([...updated]);
  }

  // Gate 1: SAST (Semgrep) — REAL
  await runGate(0, '/security/sast', { url: repoUrl, branch: repoBranch }, 'passed', 'Semgrep: 0 findings');

  // Gate 3: Secrets (Gitleaks) — REAL
  await runGate(2, '/security/secrets', { url: repoUrl, branch: repoBranch }, 'passed', 'Gitleaks: 0 secrets detected');

  // Gate 8: Artifact Store (Harbor) — always passes
  updated[7] = { ...updated[7], status: 'running', progress: 0 };
  onUpdate([...updated]);
  await simulateDelay(800);
  updated[7] = {
    ...updated[7],
    status: 'passed',
    progress: 100,
    summary: 'Harbor: Images pushed and stored',
    reportUrl: 'https://harbor.apps.sre.example.com',
    implemented: true,
  };
  onUpdate([...updated]);

  // Gate 2: SBOM (Syft) — REAL
  const imageName = `harbor.apps.sre.example.com/platform/${(repoUrl || '').split('/').pop()?.replace('.git', '') || 'app'}:latest`;
  await runGate(1, '/security/sbom', { image: imageName }, 'passed', 'SBOM generated (SPDX + CycloneDX)');

  // Gate 4: CVE Scan (Trivy) — via Harbor auto-scan, show results from proxy
  updated[3] = { ...updated[3], status: 'running', progress: 0 };
  onUpdate([...updated]);
  try {
    const vulns = await apiFetch<{ vulnerabilities: Array<{ severity: string; critical: number; high: number; medium: number; low: number; total: number; repository: string }> }>('/proxy/harbor/vulnerabilities');
    await simulateProgress(updated, 3, onUpdate, 2000);
    const allFindings = vulns.vulnerabilities.flatMap(v => {
      const findings = [];
      if (v.critical > 0) findings.push({ severity: 'critical' as const, title: `${v.critical} critical CVEs`, description: `In ${v.repository}`, location: v.repository });
      if (v.high > 0) findings.push({ severity: 'high' as const, title: `${v.high} high CVEs`, description: `In ${v.repository}`, location: v.repository });
      if (v.medium > 0) findings.push({ severity: 'medium' as const, title: `${v.medium} medium CVEs`, description: `In ${v.repository}`, location: v.repository });
      return findings;
    });
    const totalCrit = vulns.vulnerabilities.reduce((s, v) => s + v.critical, 0);
    const totalHigh = vulns.vulnerabilities.reduce((s, v) => s + v.high, 0);
    const totalMed = vulns.vulnerabilities.reduce((s, v) => s + v.medium, 0);
    updated[3] = {
      ...updated[3],
      status: totalCrit > 0 ? 'failed' : totalHigh > 0 ? 'warning' : 'passed',
      progress: 100,
      summary: `Trivy: ${totalCrit} critical, ${totalHigh} high, ${totalMed} medium`,
      findings: allFindings,
      reportUrl: 'https://harbor.apps.sre.example.com/harbor/projects',
      implemented: true,
    };
  } catch {
    await simulateProgress(updated, 3, onUpdate, 2000);
    updated[3] = {
      ...updated[3], status: 'warning', progress: 100,
      summary: 'Trivy: scan results pending (check Harbor)',
      findings: [], implemented: true,
    };
  }
  onUpdate([...updated]);

  // Gate 5: DAST (ZAP) — REAL (runs against target URL if available)
  await runGate(4, '/security/dast', { targetUrl: `https://${(repoUrl || '').split('/').pop()?.replace('.git', '') || 'app'}.apps.sre.example.com` }, 'passed', 'ZAP: 0 alerts');

  // Gate 6: ISSM Review — manual approval (always requires human)
  updated[5] = {
    ...updated[5],
    status: 'skipped',
    progress: 100,
    summary: 'Awaiting ISSM review and approval',
    implemented: false,
  };
  onUpdate([...updated]);

  // Gate 7: Image Signing — manual until Cosign is wired
  updated[6] = {
    ...updated[6],
    status: 'skipped',
    progress: 100,
    summary: 'Awaiting ISSM approval before signing',
    implemented: false,
  };
  onUpdate([...updated]);

  return updated;
}

export function getInitialDeploySteps(): DeployStep[] {
  return [
    { id: 'namespace', label: 'Namespace created', status: 'pending' },
    { id: 'pull-secret', label: 'Harbor pull secret configured', status: 'pending' },
    { id: 'helm-release', label: 'HelmRelease created', status: 'pending' },
    { id: 'pods', label: 'Pods starting', status: 'pending' },
    { id: 'health', label: 'Health check', status: 'pending' },
    { id: 'portal', label: 'Portal registration', status: 'pending' },
  ];
}

export async function runDeploy(
  appName: string,
  gitUrl: string,
  branch: string,
  team: string,
  steps: DeployStep[],
  onUpdate: (steps: DeployStep[]) => void
): Promise<{ url: string; steps: DeployStep[] }> {
  const updated = [...steps.map((s) => ({ ...s }))];

  // Step 1: Create namespace
  updated[0] = { ...updated[0], status: 'running' };
  onUpdate([...updated]);

  try {
    // Call the real deploy API
    const response = await fetch('/api/deploy/git', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify({
        url: gitUrl,
        branch: branch || 'main',
        team: team || 'team-alpha',
        appName: appName,
      }),
    });

    if (!response.ok) {
      const err = await response.json().catch(() => ({ error: 'Deploy failed' }));
      throw new Error(err.error || `HTTP ${response.status}`);
    }

    const result = await response.json();

    // Mark all steps as completed
    for (let i = 0; i < updated.length; i++) {
      updated[i] = { ...updated[i], status: 'completed' };
      onUpdate([...updated]);
      await simulateDelay(500);
    }

    const url = result.url || `https://${appName}.apps.sre.example.com`;
    return { url, steps: updated };
  } catch (err) {
    // Mark current step as failed
    const failIdx = updated.findIndex((s) => s.status === 'running');
    if (failIdx >= 0) {
      updated[failIdx] = { ...updated[failIdx], status: 'failed' };
      onUpdate([...updated]);
    }
    throw err;
  }
}

// Helpers

function simulateDelay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function simulateProgress(
  gates: SecurityGate[],
  index: number,
  onUpdate: (gates: SecurityGate[]) => void,
  totalMs: number
): Promise<void> {
  const steps = 10;
  const interval = totalMs / steps;
  for (let i = 1; i <= steps; i++) {
    await simulateDelay(interval);
    gates[index] = { ...gates[index], progress: i * 10 };
    onUpdate([...gates]);
  }
}
