{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sre-api-service.fullname" . }}
  labels:
    {{- include "sre-api-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "sre-api-service.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from same namespace (other services in the team)
    - from:
        - podSelector: {}
      ports:
        - port: {{ .Values.app.port }}
          protocol: TCP
    # Allow Prometheus scraping from monitoring namespace
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - port: {{ .Values.app.port }}
          protocol: TCP
    {{- if .Values.authorizationPolicy.enabled }}
    # Allow traffic from namespaces listed in authorizationPolicy.allowedNamespaces
    {{- range .Values.authorizationPolicy.allowedNamespaces }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .namespace }}
      ports:
        - port: {{ $.Values.app.port }}
          protocol: TCP
    {{- end }}
    # Allow traffic from namespaces listed in authorizationPolicy.allowedCallers
    {{- range .Values.authorizationPolicy.allowedCallers }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .namespace }}
      ports:
        - port: {{ $.Values.app.port }}
          protocol: TCP
    {{- end }}
    {{- end }}
    {{- with .Values.networkPolicy.additionalIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    # Allow traffic to same namespace
    - to:
        - podSelector: {}
    # Allow HTTPS egress (for external APIs)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 443
          protocol: TCP
    {{- with .Values.networkPolicy.additionalEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
