{{- range .Values.externalServices }}
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ include "sre-api-service.fullname" $ }}-{{ .host | replace "." "-" }}
  labels:
    {{- include "sre-api-service.labels" $ | nindent 4 }}
spec:
  hosts:
    - {{ .host | quote }}
  location: MESH_EXTERNAL
  ports:
    - number: {{ .port | default 443 }}
      name: {{ if eq (int (.port | default 443)) 443 }}https{{ else }}tcp-{{ .port }}{{ end }}
      protocol: {{ if eq (int (.port | default 443)) 443 }}TLS{{ else }}TCP{{ end }}
  resolution: DNS
{{- end }}
