{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sre-api-service.fullname" . }}
  labels:
    {{- include "sre-api-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sre-api-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
