# Generated by quickstart-proxmox.sh at 2026-03-05T20:05:30Z
proxmox_endpoint = "https://192.168.2.67:8006"
proxmox_insecure = true
proxmox_node     = "pve"
storage_pool     = "local-lvm"
template_name    = "sre-rocky9-rke2"

server_count  = 1
agent_count   = 2
server_cores  = 4
server_memory = 8192
agent_cores   = 4
agent_memory  = 8192

network_bridge = "vmbr0"
ip_config      = "dhcp"
