---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 10m
  chart:
    spec:
      chart: keycloak
      version: "24.8.1"
      sourceRef:
        # Bitnami charts now require OCI-type HelmRepository
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
  dependsOn:
    - name: istio-base
      namespace: istio-system
    - name: cert-manager
      namespace: cert-manager
    - name: openbao
      namespace: openbao
    - name: kube-prometheus-stack
      namespace: monitoring
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # ---------------------------------------------------------------
    # Global — allow bitnamilegacy images (migrated from bitnami org)
    # ---------------------------------------------------------------
    global:
      security:
        allowInsecureImages: true

    # ---------------------------------------------------------------
    # Keycloak image — Bitnami migrated images to bitnamilegacy org
    # ---------------------------------------------------------------
    image:
      registry: docker.io
      repository: bitnamilegacy/keycloak
      tag: "26.3.2-debian-12-r0"

    # ---------------------------------------------------------------
    # Authentication
    # ---------------------------------------------------------------
    auth:
      adminUser: "admin"
      # adminPassword is injected via valuesFrom Secret

    # ---------------------------------------------------------------
    # Deployment — production defaults
    # ---------------------------------------------------------------
    replicaCount: 2
    production: true
    proxy: "edge"

    # ---------------------------------------------------------------
    # Service — ClusterIP (accessed via Istio Gateway + VirtualService)
    # ---------------------------------------------------------------
    service:
      type: ClusterIP

    # ---------------------------------------------------------------
    # Bundled PostgreSQL — bitnamilegacy images with persistence
    # ---------------------------------------------------------------
    postgresql:
      enabled: true
      image:
        registry: docker.io
        repository: bitnamilegacy/postgresql
        tag: "17.4.0-debian-12-r17"
      primary:
        # Persistence configured via environment profile ConfigMap (keycloak-env-values)

    # ---------------------------------------------------------------
    # Prometheus Metrics
    # ---------------------------------------------------------------
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  valuesFrom:
    - kind: Secret
      name: keycloak-admin-credentials
      optional: true
    - kind: ConfigMap
      name: keycloak-env-values
      optional: true
