---
apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
  labels:
    istio-injection: enabled
    app.kubernetes.io/part-of: sre-platform
    pod-security.kubernetes.io/enforce: restricted
    sre.io/network-policy-configured: "true"
