---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
  namespace: openbao
spec:
  interval: 10m
  chart:
    spec:
      chart: openbao
      version: "0.9.0"
      sourceRef:
        kind: HelmRepository
        name: openbao
        namespace: flux-system
  dependsOn:
    - name: istio-base
      namespace: istio-system
    - name: kube-prometheus-stack
      namespace: monitoring
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    server:
      # Production mode — HA Raft storage cluster
      # For single-node/dev, override via environment profile ConfigMap
      dev:
        enabled: false
      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          config: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "raft" {
              path = "/openbao/data"
            }
            service_registration "kubernetes" {}
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      service:
        type: ClusterIP
      dataStorage:
        enabled: true
        size: 10Gi
      extraEnvironmentVars:
        OPENBAO_LOG_LEVEL: "info"
    injector:
      enabled: false
    ui:
      enabled: true
    csi:
      enabled: false
    serverTelemetry:
      serviceMonitor:
        enabled: true
  valuesFrom:
    - kind: Secret
      name: openbao-seal-credentials
      optional: true
    - kind: ConfigMap
      name: openbao-env-values
      optional: true
