---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
  namespace: openbao
spec:
  interval: 10m
  chart:
    spec:
      chart: openbao
      version: "0.9.0"
      sourceRef:
        kind: HelmRepository
        name: openbao
        namespace: flux-system
  dependsOn:
    - name: istio-base
      namespace: istio-system
    - name: kube-prometheus-stack
      namespace: monitoring
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    server:
      # Dev mode for lab — uses in-memory storage, auto-unsealed
      # For production, use HA mode with Raft storage and transit/KMS seal
      dev:
        enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      service:
        type: NodePort
        nodePort: 30200
      extraEnvironmentVars:
        OPENBAO_LOG_LEVEL: "info"
    injector:
      enabled: false
    ui:
      enabled: true
    csi:
      enabled: false
    serverTelemetry:
      serviceMonitor:
        enabled: true
  valuesFrom:
    - kind: Secret
      name: openbao-seal-credentials
      optional: true
