---
# Flux Kustomization for logging (Loki + Alloy)
# Depends on: istio, monitoring
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sre-logging
  namespace: flux-system
  annotations:
    sre.io/nist-controls: "AU-2, AU-3, AU-4, AU-9, AU-12"
spec:
  interval: 10m
  path: ./platform/core/logging
  prune: true
  sourceRef:
    kind: GitRepository
    name: sre-platform
  dependsOn:
    - name: sre-istio
    - name: sre-monitoring
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: loki
      namespace: logging
    - apiVersion: apps/v1
      kind: DaemonSet
      name: alloy
      namespace: logging
  timeout: 10m
