---
# Flux Kustomization for monitoring (kube-prometheus-stack)
# Depends on: istio, kyverno
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sre-monitoring
  namespace: flux-system
  annotations:
    sre.io/nist-controls: "AU-6, CA-7, IR-4, IR-5, SI-4"
spec:
  interval: 10m
  path: ./platform/core/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: sre-platform
  dependsOn:
    - name: sre-istio
    - name: sre-kyverno
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kube-prometheus-stack-grafana
      namespace: monitoring
    - apiVersion: apps/v1
      kind: StatefulSet
      name: prometheus-kube-prometheus-stack-kube-prom-prometheus
      namespace: monitoring
  timeout: 10m
