---
# Grafana datasource for Loki — deployed in monitoring namespace
# so the Grafana sidecar auto-discovers it via the grafana_datasource label.
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/part-of: sre-platform
  annotations:
    sre.io/nist-controls: "AU-6"
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.logging.svc.cluster.local:80
        isDefault: false
        editable: false
        jsonData:
          maxLines: 1000
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: '"traceID":"(\w+)"'
              name: TraceID
              url: "$${__value.raw}"
