---
# Loki — Log aggregation engine (SingleBinary mode)
# Chart: grafana/loki
# Docs: https://grafana.com/docs/loki/latest/
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
  annotations:
    sre.io/nist-controls: "AU-2, AU-3, AU-4, AU-9, AU-12"
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: "6.29.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  dependsOn:
    - name: istio-base
      namespace: istio-system
    - name: kube-prometheus-stack
      namespace: monitoring
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # ---------------------------------------------------------------
    # Deployment Mode — SingleBinary for simplicity
    # ---------------------------------------------------------------
    deploymentMode: SingleBinary

    # ---------------------------------------------------------------
    # Loki Configuration
    # ---------------------------------------------------------------
    loki:
      auth_enabled: false

      commonConfig:
        replication_factor: 1
        path_prefix: /tmp/loki

      storage:
        type: filesystem
        filesystem:
          chunks_directory: /tmp/loki/chunks
          rules_directory: /tmp/loki/rules

      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: "loki_index_"
              period: "24h"

      limits_config:
        retention_period: "720h"
        max_query_series: 500
        max_query_parallelism: 2
        reject_old_samples: true
        reject_old_samples_max_age: "168h"

      rulerConfig:
        storage:
          type: local
          local:
            directory: /tmp/loki/rules

    # ---------------------------------------------------------------
    # SingleBinary — production default with PVC persistence
    # ---------------------------------------------------------------
    singleBinary:
      replicas: 1
      # Persistence configured via environment profile ConfigMap (loki-env-values)

    # ---------------------------------------------------------------
    # Disable scaled components (not used in SingleBinary mode)
    # ---------------------------------------------------------------
    read:
      replicas: 0
    write:
      replicas: 0
    backend:
      replicas: 0
    gateway:
      enabled: false

    # ---------------------------------------------------------------
    # Disable caches (not needed for single-node deployment)
    # ---------------------------------------------------------------
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false

    # ---------------------------------------------------------------
    # Monitoring Integration
    # ---------------------------------------------------------------
    monitoring:
      serviceMonitor:
        enabled: true
        labels:
          app.kubernetes.io/part-of: sre-platform
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false

    # ---------------------------------------------------------------
    # Testing
    # ---------------------------------------------------------------
    test:
      enabled: false

  valuesFrom:
    - kind: ConfigMap
      name: loki-env-values
      optional: true
