---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sre-web-app.fullname" . }}
  labels:
    {{- include "sre-web-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.app.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sre-web-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sre-web-app.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "sre-web-app.serviceAccountName" . }}
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- include "sre-lib.podSecurityContext" . | nindent 8 }}
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          securityContext:
            {{- include "sre-lib.containerSecurityContext" . | nindent 12 }}
          resources:
            {{- include "sre-lib.resources" . | nindent 12 }}
          livenessProbe:
            {{- if eq (.Values.app.probes.liveness.type | default "http") "tcp" }}
            tcpSocket:
              port: http
            {{- else }}
            httpGet:
              path: {{ .Values.app.probes.liveness.path }}
              port: http
            {{- end }}
            initialDelaySeconds: {{ .Values.app.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.app.probes.liveness.failureThreshold | default 3 }}
          readinessProbe:
            {{- if eq (.Values.app.probes.readiness.type | default "http") "tcp" }}
            tcpSocket:
              port: http
            {{- else }}
            httpGet:
              path: {{ .Values.app.probes.readiness.path }}
              port: http
            {{- end }}
            initialDelaySeconds: {{ .Values.app.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.app.probes.readiness.failureThreshold | default 3 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /var/cache
          env:
            {{- include "sre-lib.env" . | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
