---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neuvector
  namespace: neuvector
spec:
  interval: 10m
  chart:
    spec:
      chart: core
      version: "2.7.3"
      sourceRef:
        kind: HelmRepository
        name: neuvector
        namespace: flux-system
  dependsOn:
    - name: istio-base
      namespace: istio-system
    - name: monitoring
      namespace: monitoring
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # ---------------------------------------------------------------
    # Controller — cluster management and policy engine
    # ---------------------------------------------------------------
    controller:
      replicas: 3
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi

    # ---------------------------------------------------------------
    # Enforcer — DaemonSet for runtime protection on every node
    # ---------------------------------------------------------------
    enforcer:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi

    # ---------------------------------------------------------------
    # Manager — Web UI
    # ---------------------------------------------------------------
    manager:
      enabled: true

    # ---------------------------------------------------------------
    # Scanner — image and container vulnerability scanning
    # ---------------------------------------------------------------
    scanner:
      enabled: true
      replicas: 2

    # ---------------------------------------------------------------
    # CVE Scanner
    # ---------------------------------------------------------------
    cve:
      scanner:
        enabled: true

    # ---------------------------------------------------------------
    # Admission Control Webhook
    # ---------------------------------------------------------------
    admissionwebhook:
      type: ClusterIP

    # ---------------------------------------------------------------
    # Prometheus Metrics Exporter
    # ---------------------------------------------------------------
    monitor:
      exporter:
        enabled: true
  valuesFrom:
    - kind: ConfigMap
      name: neuvector-env-values
      optional: true
