---
apiVersion: v1
kind: Namespace
metadata:
  name: neuvector
  labels:
    app.kubernetes.io/part-of: sre-platform
    pod-security.kubernetes.io/enforce: privileged
    # NO istio-injection — NeuVector needs privileged DaemonSet
