---
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: n8n-security-exception
  namespace: team-alpha
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/part-of: sre-platform
    sre.io/team: team-alpha
  annotations:
    sre.io/exception-reason: "App requires relaxed security context"
spec:
  exceptions:
    - policyName: require-security-context
      ruleNames:
        - require-run-as-non-root
        - require-drop-all-capabilities
  match:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - team-alpha
          names:
            - "n8n-*"
