---
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: ws-security-exception
  namespace: team-alpha
  labels:
    app.kubernetes.io/part-of: sre-platform
    sre.io/team: team-alpha
    sre.io/managed-by: dsop-pipeline
  annotations:
    sre.io/exception-reason: 'run_as_root: required; privileged_container: required; host_networking: required'
    sre.io/exception-approver: sre-admin@sre.example.com
    sre.io/exception-expiry: '2026-06-26'
    sre.io/pipeline-generated: 'true'
spec:
  exceptions:
    - policyName: require-run-as-nonroot
      ruleNames:
        - require-pod-run-as-nonroot
        - require-container-run-as-nonroot
    - policyName: require-security-context
      ruleNames:
        - require-run-as-non-root
        - require-drop-all-capabilities
    - policyName: disallow-privilege-escalation
      ruleNames:
        - disallow-privilege-escalation-containers
        - disallow-privilege-escalation-init-containers
    - policyName: disallow-privileged-containers
      ruleNames:
        - deny-privileged-containers
        - deny-privileged-init-containers
    - policyName: require-drop-all-capabilities
      ruleNames:
        - require-drop-all
    - policyName: disallow-host-namespaces
      ruleNames:
        - deny-host-namespaces
    - policyName: disallow-host-ports
      ruleNames:
        - deny-host-ports
        - deny-host-ports-init-containers
  match:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - team-alpha
          names:
            - ws-*
