---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  labels:
    app.kubernetes.io/part-of: sre-platform
    sre.io/policy-category: custom
  annotations:
    policies.kyverno.io/title: Disallow Latest Tag
    policies.kyverno.io/description: >-
      Blocks container images that use the :latest tag or have no tag specified.
      Using :latest or untagged images makes deployments non-reproducible and
      breaks rollback capabilities. All images must use explicit version tags.
      System namespaces are excluded from this policy.
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    sre.io/nist-controls: "CM-2"
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: validate-image-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kube-public
                - kube-node-lease
                - istio-system
                - flux-system
                - kyverno
                - cert-manager
      validate:
        message: >-
          Container images in Pod {{request.object.metadata.name}} must not use
          the :latest tag or be untagged. All images must specify an explicit
          version tag (e.g., v1.2.3). Change your image reference from
          `myimage:latest` or `myimage` to `myimage:v1.2.3`.
        pattern:
          spec:
            containers:
              - image: "!*:latest & *:*"
    - name: validate-init-container-image-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kube-public
                - kube-node-lease
                - istio-system
                - flux-system
                - kyverno
                - cert-manager
      preconditions:
        all:
          - key: "{{ request.object.spec.initContainers[] | length(@) }}"
            operator: GreaterThanOrEquals
            value: 1
      validate:
        message: >-
          Init container images in Pod {{request.object.metadata.name}} must not
          use the :latest tag or be untagged.
        pattern:
          spec:
            initContainers:
              - image: "!*:latest & *:*"
