---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - disallow-latest-tag.yaml
  - require-istio-sidecar.yaml
  - require-labels.yaml
  - require-network-policies.yaml
  - require-security-context.yaml
  - restrict-image-registries.yaml
  - verify-image-signatures.yaml
