---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-istio-sidecar
  labels:
    app.kubernetes.io/part-of: sre-platform
    sre.io/policy-category: custom
  annotations:
    policies.kyverno.io/title: Require Istio Sidecar Injection
    policies.kyverno.io/description: >-
      Ensures all non-system namespaces have Istio sidecar injection enabled.
      Namespaces must include the label `istio-injection: enabled` to be part
      of the service mesh. System namespaces (kube-system, kube-public,
      kube-node-lease, istio-system, flux-system) are excluded.
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: high
    sre.io/nist-controls: "SC-8, AC-4"
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-istio-injection-label
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kube-public
                - kube-node-lease
                - istio-system
                - flux-system
                - kyverno
                - cert-manager
                - monitoring
                - logging
                - tempo
                - openbao
                - external-secrets
                - neuvector
                - harbor
                - velero
                - keycloak
                - default
          - resources:
              selector:
                matchLabels:
                  sre.io/system-namespace: "true"
      validate:
        message: >-
          Namespace {{request.object.metadata.name}} must have the label
          `istio-injection: enabled` to participate in the service mesh.
          Add the label: kubectl label namespace {{request.object.metadata.name}} istio-injection=enabled
        pattern:
          metadata:
            labels:
              istio-injection: "enabled"
