---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-network-policies
  labels:
    app.kubernetes.io/part-of: sre-platform
    sre.io/policy-category: custom
  annotations:
    policies.kyverno.io/title: Require Network Policies
    policies.kyverno.io/description: >-
      Requires every non-system namespace to have at least one NetworkPolicy
      defined. Namespaces without NetworkPolicies have unrestricted network
      access, which violates the principle of least privilege for network
      communication. System namespaces are excluded from this policy.
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: high
    sre.io/nist-controls: "SC-7, AC-4"
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-network-policy-exists
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kube-public
                - kube-node-lease
                - istio-system
                - flux-system
                - kyverno
                - cert-manager
      validate:
        message: >-
          Namespace {{request.object.metadata.name}} must have at least one
          NetworkPolicy. Create a default-deny NetworkPolicy for the namespace:
          kubectl apply -f - <<EOF
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: default-deny-all
            namespace: {{request.object.metadata.name}}
          spec:
            podSelector: {}
            policyTypes:
            - Ingress
            - Egress
          EOF
        pattern:
          metadata:
            labels:
              sre.io/network-policy-configured: "true"
