---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  creationTimestamp: '2026-03-15T20:39:28Z'
  finalizers:
    - finalizers.fluxcd.io
  generation: 8
  labels:
    app.kubernetes.io/part-of: sre-platform
    sre.io/team: team-keystone
  managedFields:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"finalizers.fluxcd.io": {}
      manager: helm-controller
      operation: Update
      time: '2026-03-15T20:39:28Z'
    - apiVersion: helm.toolkit.fluxcd.io/v2
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app.kubernetes.io/part-of: {}
            f:sre.io/team: {}
        f:spec:
          .: {}
          f:chart:
            .: {}
            f:spec:
              .: {}
              f:chart: {}
              f:reconcileStrategy: {}
              f:sourceRef:
                .: {}
                f:kind: {}
                f:name: {}
                f:namespace: {}
              f:version: {}
          f:install:
            .: {}
            f:createNamespace: {}
            f:remediation:
              .: {}
              f:retries: {}
          f:interval: {}
          f:upgrade:
            .: {}
            f:cleanupOnFail: {}
            f:remediation:
              .: {}
              f:retries: {}
          f:values:
            .: {}
            f:app:
              .: {}
              f:env: {}
              f:image:
                .: {}
                f:pullPolicy: {}
                f:repository: {}
              f:name: {}
              f:port: {}
              f:probes:
                .: {}
                f:liveness:
                  .: {}
                  f:initialDelaySeconds: {}
                  f:path: {}
                  f:periodSeconds: {}
                f:readiness:
                  .: {}
                  f:initialDelaySeconds: {}
                  f:path: {}
                  f:periodSeconds: {}
              f:replicas: {}
              f:resources:
                .: {}
                f:limits:
                  .: {}
                  f:cpu: {}
                  f:memory: {}
                f:requests:
                  .: {}
                  f:cpu: {}
                  f:memory: {}
              f:team: {}
            f:autoscaling:
              .: {}
              f:enabled: {}
            f:ingress:
              .: {}
              f:enabled: {}
              f:host: {}
            f:networkPolicy:
              .: {}
              f:enabled: {}
            f:podDisruptionBudget:
              .: {}
              f:enabled: {}
            f:serviceMonitor:
              .: {}
              f:enabled: {}
      manager: unknown
      operation: Update
      time: '2026-03-15T20:39:28Z'
    - apiVersion: helm.toolkit.fluxcd.io/v2
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:values:
            f:app:
              f:image:
                f:tag: {}
      manager: kubectl-patch
      operation: Update
      time: '2026-03-16T17:17:42Z'
    - apiVersion: helm.toolkit.fluxcd.io/v2
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions: {}
          f:helmChart: {}
          f:history: {}
          f:inventory:
            .: {}
            f:entries: {}
          f:lastAttemptedConfigDigest: {}
          f:lastAttemptedGeneration: {}
          f:lastAttemptedReleaseAction: {}
          f:lastAttemptedReleaseActionDuration: {}
          f:lastAttemptedRevision: {}
          f:observedGeneration: {}
          f:storageNamespace: {}
      manager: helm-controller
      operation: Update
      subresource: status
      time: '2026-03-17T18:11:42Z'
  name: keystone-frontend
  namespace: team-keystone
  resourceVersion: '7065341'
  uid: d66e77bc-974f-4555-abd9-662a84784360
spec:
  chart:
    spec:
      chart: ./apps/templates/web-app
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      version: '*'
  install:
    createNamespace: false
    remediation:
      retries: 3
  interval: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    app:
      env: []
      image:
        pullPolicy: IfNotPresent
        repository: harbor.apps.sre.example.com/keystone/keystone-frontend
        tag: build-sso-v5
      name: keystone-frontend
      port: 8080
      probes:
        liveness:
          initialDelaySeconds: 10
          path: /
          periodSeconds: 10
        readiness:
          initialDelaySeconds: 5
          path: /
          periodSeconds: 5
      replicas: 1
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 64Mi
      team: team-keystone
    autoscaling:
      enabled: false
    ingress:
      enabled: true
      host: keystone.apps.sre.example.com
    networkPolicy:
      enabled: true
    podDisruptionBudget:
      enabled: false
    serviceMonitor:
      enabled: false
status:
  conditions:
    - lastTransitionTime: '2026-03-17T18:11:42Z'
      message: Helm upgrade succeeded for release team-keystone/keystone-frontend.v39 with chart sre-web-app@0.5.0+85429ebc5455
      observedGeneration: 8
      reason: UpgradeSucceeded
      status: 'True'
      type: Ready
    - lastTransitionTime: '2026-03-17T18:11:42Z'
      message: Helm upgrade succeeded for release team-keystone/keystone-frontend.v39 with chart sre-web-app@0.5.0+85429ebc5455
      observedGeneration: 8
      reason: UpgradeSucceeded
      status: 'True'
      type: Released
  helmChart: flux-system/team-keystone-keystone-frontend
  history:
    - action: upgrade
      apiVersion: v2
      appVersion: 1.0.0
      chartName: sre-web-app
      chartVersion: 0.5.0+85429ebc5455
      configDigest: sha256:b644e1ac0a64bbbbad0ba71cf806b24b16f670e430c2a23883599fa4a007e3f6
      digest: sha256:474bc1aaa9ff96bbf6219793c17128e01f5b4cf19a797e1bd9ff92cfce2104ab
      firstDeployed: '2026-03-15T20:39:30Z'
      lastDeployed: '2026-03-17T18:11:42Z'
      name: keystone-frontend
      namespace: team-keystone
      status: deployed
      version: 39
    - apiVersion: v2
      appVersion: 1.0.0
      chartName: sre-web-app
      chartVersion: 0.5.0+870d7941503d
      configDigest: sha256:b644e1ac0a64bbbbad0ba71cf806b24b16f670e430c2a23883599fa4a007e3f6
      digest: sha256:72b15179156cc399be93bb45b9ab36dd4edf6020bcbd0967f9cdc7a1a0cbe840
      firstDeployed: '2026-03-15T20:39:30Z'
      lastDeployed: '2026-03-17T18:09:37Z'
      name: keystone-frontend
      namespace: team-keystone
      status: superseded
      version: 38
  inventory:
    entries:
      - id: team-keystone_keystone-frontend-keystone-frontend_networking.k8s.io_NetworkPolicy
        v: v1
      - id: team-keystone_keystone-frontend-keystone-frontend__ServiceAccount
        v: v1
      - id: team-keystone_keystone-frontend-keystone-frontend__Service
        v: v1
      - id: team-keystone_keystone-frontend-keystone-frontend_apps_Deployment
        v: v1
      - id: team-keystone_keystone-frontend-keystone-frontend_networking.istio.io_VirtualService
        v: v1beta1
  lastAttemptedConfigDigest: sha256:b644e1ac0a64bbbbad0ba71cf806b24b16f670e430c2a23883599fa4a007e3f6
  lastAttemptedGeneration: 8
  lastAttemptedReleaseAction: upgrade
  lastAttemptedReleaseActionDuration: 744.169963ms
  lastAttemptedRevision: 0.5.0+85429ebc5455
  observedGeneration: 8
  storageNamespace: team-keystone
