---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keystone-frontend
  namespace: team-keystone
  labels:
    app.kubernetes.io/part-of: sre-platform
    sre.io/team: team-keystone
spec:
  interval: 10m
  chart:
    spec:
      chart: ./apps/templates/web-app
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    app:
      env: []
      image:
        pullPolicy: IfNotPresent
        repository: harbor.apps.sre.example.com/keystone/keystone-frontend
        tag: build-sso-v5
      name: keystone-frontend
      port: 8080
      probes:
        liveness:
          initialDelaySeconds: 10
          path: /
          periodSeconds: 10
        readiness:
          initialDelaySeconds: 5
          path: /
          periodSeconds: 5
      replicas: 1
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 64Mi
      team: team-keystone
    autoscaling:
      enabled: false
    ingress:
      enabled: true
      host: keystone.apps.sre.example.com
    networkPolicy:
      enabled: true
    podDisruptionBudget:
      enabled: false
    serviceMonitor:
      enabled: false
