---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: go-httpbin
  namespace: team-test
  labels:
    app.kubernetes.io/part-of: sre-platform
    sre.io/team: team-test
spec:
  interval: 10m
  chart:
    spec:
      chart: ./apps/templates/web-app
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    app:
      name: go-httpbin
      team: team-test
      image:
        repository: harbor.apps.sre.example.com/team-test/go-httpbin
        tag: v0.1.0
        pullPolicy: IfNotPresent
      port: 8080
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      probes:
        liveness:
          path: /status/200
          initialDelaySeconds: 10
          periodSeconds: 10
        readiness:
          path: /status/200
          initialDelaySeconds: 5
          periodSeconds: 5
      env: []
    autoscaling:
      enabled: false
    networkPolicy:
      enabled: true
    podDisruptionBudget:
      enabled: false
    serviceMonitor:
      enabled: false
    ingress:
      enabled: true
      host: go-httpbin.apps.sre.example.com
