---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - go-httpbin.yaml
  - go-httpbin-policy-exception.yaml
  - uptime-kuma.yaml
  - uptime-kuma-policy-exception.yaml
  - gitea.yaml
