---
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: uptime-kuma-security-exception
  namespace: team-test
  labels:
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/part-of: sre-platform
    sre.io/team: team-test
  annotations:
    sre.io/exception-reason: "uptime-kuma requires root + SETGID/SETUID capabilities"
    sre.io/exception-approver: "platform-team"
spec:
  exceptions:
    - policyName: require-security-context
      ruleNames:
        - require-run-as-non-root
        - require-drop-all-capabilities
    - policyName: require-run-as-nonroot
      ruleNames:
        - require-pod-run-as-nonroot
        - require-container-run-as-nonroot
  match:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - team-test
          names:
            - "uptime-kuma-*"
