---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: dsop-wizard
  namespace: sre-dsop
  labels:
    app.kubernetes.io/name: dsop-wizard
    app.kubernetes.io/part-of: sre-platform
spec:
  hosts:
    - "dsop.${SRE_DOMAIN}"
  gateways:
    - istio-system/main
  http:
    - route:
        - destination:
            host: dsop-wizard.sre-dsop.svc.cluster.local
            port:
              number: 8080
