---
# Grafana datasource for Tempo — deployed in monitoring namespace
# so the Grafana sidecar auto-discovers it via the grafana_datasource label.
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-tempo
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/part-of: sre-platform
  annotations:
    sre.io/nist-controls: "AU-2, SI-4"
data:
  tempo-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        uid: tempo
        access: proxy
        url: http://tempo.tempo.svc.cluster.local:3100
        isDefault: false
        editable: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            filterByTraceID: true
            filterBySpanID: true
          tracesToMetrics:
            datasourceUid: prometheus
          serviceMap:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true
          lokiSearch:
            datasourceUid: loki
