---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  interval: 10m
  chart:
    spec:
      chart: tempo
      version: "1.18.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  dependsOn:
    - name: istio-base
      namespace: istio-system
    - name: kube-prometheus-stack
      namespace: monitoring
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # ---------------------------------------------------------------
    # Tempo Configuration
    # ---------------------------------------------------------------
    tempo:
      receivers:
        zipkin:
          endpoint: "0.0.0.0:9411"
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"
      metricsGenerator:
        enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi

    # ---------------------------------------------------------------
    # Security Context — required for PodSecurity restricted
    # ---------------------------------------------------------------
    securityContext:
      runAsNonRoot: true
      runAsUser: 10001
      runAsGroup: 10001
      fsGroup: 10001
      seccompProfile:
        type: RuntimeDefault

    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL

    # ---------------------------------------------------------------
    # Persistence — disabled for lab (no StorageClass)
    # ---------------------------------------------------------------
    persistence:
      enabled: false

    # ---------------------------------------------------------------
    # Prometheus ServiceMonitor
    # ---------------------------------------------------------------
    serviceMonitor:
      enabled: true
  valuesFrom:
    - kind: ConfigMap
      name: tempo-env-values
      optional: true
