---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-env-values
  namespace: monitoring
data:
  values.yaml: |
    prometheus:
      prometheusSpec:
        replicas: 1
        retention: "15d"
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
    grafana:
      replicas: 1
      persistence:
        enabled: true
        storageClassName: local-path
        size: 5Gi
    alertmanager:
      alertmanagerSpec:
        replicas: 1
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 2Gi
