---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-env-values
  namespace: openbao
data:
  values.yaml: |
    server:
      dev:
        enabled: false
      ha:
        enabled: false
      standalone:
        enabled: true
      dataStorage:
        enabled: true
        storageClass: local-path
        size: 5Gi
